[13.0][ADD] l10n_th_hr_employee_id_validation module
OCA/l10n-thailand pull request #222
Opened 2021-01-29 05:18 UTC by piruin

This module added validation for Identification No of Employee who is a citizen of Thailand.

Validation only occurs when Employee's Nationality is Thailand and Identification No is present.
- Must be digits with 13 lengths
- Verify checksum at last digit

2021-02-03 05:19 UTC, sansirit commented
ผมคิดว่าควรเพิ่มความสามารถในการตรวจและแก้ไขข้อมูลตามนี้ครับ
- ผู้ใช้ป้อนข้อมูลเลขประจำตัวประชาชนในรูปแบบใดก็ได้ ไม่ว่าจะเป็น 1-2345-67890-12-1 หรือ 1 2345 67890 12 1 หรือรูปแบบใดๆ ที่มีอักขระใดๆ อยู่ก็ได้
- method @onchange หรือ @depends ทำการดึงอักขระตัวเลขออกมาเท่านั้นในการตรวจสอบ และบันทึกข้อมูลลงใน field ดังนี้
`import re

@api.depends('identification_id', 'country_id')
def _preprocess_identification_id(self):
    for record in self:
        if "TH" == record.country_id.code and record.identification_id:
            record.identification_id = re.findall('^[0-9]+', identification_id)[0]`

ประโยชน์ที่ได้ก็คือ จะทำให้ user friendly ดีมากขึ้น

2021-02-03 05:19 UTC, sansirit requested changes
ผมคิดว่าควรเพิ่มความสามารถในการตรวจและแก้ไขข้อมูลตามนี้ครับ
- ผู้ใช้ป้อนข้อมูลเลขประจำตัวประชาชนในรูปแบบใดก็ได้ ไม่ว่าจะเป็น 1-2345-67890-12-1 หรือ 1 2345 67890 12 1 หรือรูปแบบใดๆ ที่มีอักขระใดๆ อยู่ก็ได้
- method @onchange หรือ @depends ทำการดึงอักขระตัวเลขออกมาเท่านั้นในการตรวจสอบ และบันทึกข้อมูลลงใน field ดังนี้
`import re

@api.depends('identification_id', 'country_id')
def _preprocess_identification_id(self):
    for record in self:
        if "TH" == record.country_id.code and record.identification_id:
            record.identification_id = re.findall('^[0-9]+', identification_id)[0]`

ประโยชน์ที่ได้ก็คือ จะทำให้ user friendly ดีมากขึ้น

2021-02-03 05:19 UTC, sansirit commented on l10n_th_hr_employee_id_validation/models/hr_employee.py
> +def validate_th_id_checksum(_id):
ผมคิดว่าควรรวม method นี้เข้าไปอยู่ใน method hr.employee._check_identification_id เพราะมีเพียง 4 บรรทัด และผมไม่ควรมี global method แบบนี้

2021-02-03 05:19 UTC, sansirit commented on l10n_th_hr_employee_id_validation/models/hr_employee.py
> +def validate_th_id_format(_id):
ผมคิดว่าควรรวม method นี้เข้าไปอยู่ใน method hr.employee._check_identification_id เพราะมีเพียง 2 บรรทัด และผมไม่ควรมี global method แบบนี้

2021-02-03 05:19 UTC, sansirit commented on l10n_th_hr_employee_id_validation/models/hr_employee.py
> +    def _check_identificaiont_id(self):
เปลี่ยนคำผิดที่ชื่อ method
และควรรวม validate_th_id_checksum และ validate_th_id_format เข้ามาใน _check_identification_id

2021-02-03 05:19 UTC, sansirit commented on l10n_th_hr_employee_id_validation/models/hr_employee.py
> +
ผมคิดว่าควรเพิ่ม @api.depend เพื่อลบอักขระที่ไม่ใช่ตัวเลขออกทั้งหมด โดยใช้ regex แบบนี้ครับ
import re
record.identification_id = re.findall('^[0-9]+', identification_id)[0]

2021-02-06 03:27 UTC, kittiu commented on l10n_th_hr_employee_id_validation/models/hr_employee.py
> +    def _check_identificaiont_id(self):
Misspell, identificaiont -> identification

2021-02-13 05:24 UTC, kittiu commented
Sorry for delayed response, I was also looking into how other country manage this kind of feature.

I would say I am ok with the code now. Just final comment from me,

I think the module name can be more self explained. Do you think it better change to `l10n_th_employee_identification_id` (is enough for me) or `l10n_th_employee_identification_id_verification`, WDYT?

**Note:** Also, I have been looking around for options, may be the technique used here will interest you. In future we could have a module like, `l10n_th_fields_verification` to cover all thai related field in the future.

* https://github.com/OCA/partner-contact/blob/13.0/partner_identification/models/res_partner_id_category.py#L55
* https://github.com/OCA/server-tools/tree/13.0/base_exception

Again, thanks for your contribution!

2021-02-13 05:26 UTC, kittiu approved these changes

2021-02-14 05:06 UTC, piruin commented
Should we use `l10n_th_hr_employee_identification_id` instead? follow the [OCA Guildine](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#11modules). 

> - When creating a localization module, prefix its name with l10n_CC_, where CC is its country code. I.e. l10n_es_pos.
> - When extending an Odoo module, prefix yours with that module's name. I.e. mail_forward.

Please collect me if I misunderstood.

Thank you for your review

2021-02-14 06:35 UTC, kittiu commented
> Should we use `l10n_th_hr_employee_identification_id` instead? follow the [OCA Guildine](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#11modules).
> 
> > * When creating a localization module, prefix its name with l10n_CC_, where CC is its country code. I.e. l10n_es_pos.
> > * When extending an Odoo module, prefix yours with that module's name. I.e. mail_forward.
> 
> Please collect me if I misunderstood.
> 
> Thank you for your review

Ok for me.

2021-02-16 01:13 UTC, kittiu commented
Please squash all coomits ito 1 commit.
Note: we need one more approve to merge.

2021-02-16 03:19 UTC, sansirit approved these changes
I accept the change and the proposed name.

2021-02-16 03:21 UTC, kittiu commented
/ocabot merge nobump

2021-02-16 08:03 UTC, piruin commented
> Please squash all coomits ito 1 commit.

Done

2021-02-16 08:17 UTC, kittiu commented
/ocabot merge nobump

2021-02-16 11:11 UTC, merged