[16.0][FIX] l10n_th_account: create wht certs only wht move have a wht tax id
OCA/l10n-thailand pull request #478
Opened 2024-11-11 04:44 UTC by Pani-k-folk

Create wht certs only wht move have a wht tax id

2024-11-11 10:09 UTC, Saran440 requested changes
please, provide step to error.

and I think we should fixed error with line https://github.com/OCA/l10n-thailand/pull/478/files#diff-8fdb10d323cb0a62e8c6a2ee4c53aef21d7c0641da8b451e3de3be80aa778b6fR548

for filter account withholding tax **and wht** is selected

`wht_moves = move.line_ids.filtered(lambda l: l.account_id.wht_account and l.wht_tax_id)`

2024-11-13 09:28 UTC, Pani-k-folk commented
@Saran440 
I have revised and tested it following your suggestions. It works well and resolved the issue entirely. Thanks for your help.

2024-11-13 11:01 UTC, Saran440 approved these changes
LGTM :+1:

2025-02-28 05:05 UTC, Saran440 commented
/ocabot merge patch

2025-02-28 05:09 UTC, merged